[package]
name = "actionx_voting"
version = "1.0.0"
authors = []

[addresses]
voting = "48f02a18ecbfc5e009c407d0b751293f51900dcd3e953f52f9be8df26d842159"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
